import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
    paddingTop: 40,
    paddingBottom: 12,
    paddingHorizontal: 16,
  },
  header: {
    marginBottom: 8,
  },
    title: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 24,
    textAlign: 'center',
    color: '#111',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  },
  input: {
    flex: 1,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#111',
  },
  inputError: {
    borderColor: '#ff3b30',
  },
  saveButton: {
    backgroundColor: '#111',
    borderRadius: 14,
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    color: '#ff3b30',
    fontSize: 12,
    marginBottom: 6,
    marginLeft: 4,
  },
  warningText: {
    color: '#ff9500',
    fontSize: 12,
    marginBottom: 6,
    marginLeft: 4,
  },
  filterBar: {
    marginTop: 10,
    marginBottom: 4,
  },
  filterBarContent: {
    gap: 8,
    alignItems: 'center',
    paddingVertical: 2,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  filterChipActive: {
    backgroundColor: '#111',
    borderColor: '#111',
  },
  filterChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#888',
  },
  filterChipTextActive: {
    color: '#fff',
  },
  list: {
    flex: 1,
    marginTop: 8,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#fff',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  cardBody: {
    flex: 1,
  },
  person: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111',
  },
  note: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  },
  noNote: {
    fontSize: 12,
    color: '#ccc',
    marginTop: 2,
    fontStyle: 'italic',
  },
  right: {
    alignItems: 'flex-end',
  },
  amount: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111',
  },
  date: {
    fontSize: 11,
    color: '#bbb',
    marginTop: 2,
  },
  deleteAction: {
    backgroundColor: '#ff3b30',
    justifyContent: 'center',
    alignItems: 'center',
    width: 72,
    borderRadius: 14,
    marginBottom: 8,
  },
  editAction: {
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    width: 72,
    borderRadius: 14,
    marginBottom: 8,
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    marginTop: 4,
  },
  totalLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#888',
  },
  totalAmount: {
    fontSize: 22,
    fontWeight: '800',
    color: '#111',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 60,
    gap: 8,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ccc',
  },
  emptySubtext: {
    fontSize: 13,
    color: '#ddd',
  },
});