import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    paddingTop: 80,
    padding: 24,
  },
  title: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 24,
    textAlign: 'center',
    color: '#111',
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: '#111',
    marginBottom: 16,
  },
  button: {
    width: '100%',
    backgroundColor: '#111',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 24,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  list: { width: '100%' },
  card: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#f5f5f5',
    marginBottom: 10,
  },
  person: { fontSize: 16, fontWeight: '600', color: '#111' },
  note: { fontSize: 13, color: '#666', marginTop: 2 },
  amount: { fontSize: 16, fontWeight: '700', color: '#111', textAlign: 'right' },
  date: { fontSize: 12, color: '#999', textAlign: 'right', marginTop: 2 },
  right: { alignItems: 'flex-end' },
  inputError: {
  borderColor: '#ff3b30',
},
errorText: {
  width: '100%',
  color: '#ff3b30',
  fontSize: 13,
  marginBottom: 8,
  marginTop: -8,
},
warningText: {
  width: '100%',
  color: '#ff9500',
  fontSize: 13,
  marginBottom: 8,
  marginTop: -8,
},
noNote: {
  fontSize: 13,
  color: '#bbb',
  marginTop: 2,
  fontStyle: 'italic',
},
deleteAction: {
  backgroundColor: '#ff3b30',
  justifyContent: 'center',
  alignItems: 'center',
  width: 80,
  borderRadius: 12,
  marginBottom: 10,
},
deleteActionText: {
  fontSize: 24,
},
editIcon: {
  marginTop: 6,
  alignSelf: 'flex-end',
},
editIconText: {
  fontSize: 16,
},
editAction: {
  backgroundColor: '#007AFF',
  justifyContent: 'center',
  alignItems: 'center',
  width: 80,
  borderRadius: 12,
  marginBottom: 10,
},
editActionText: {
  fontSize: 24,
},
totalContainer: {
  width: '100%',
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingVertical: 12,
  paddingHorizontal: 4,
  marginBottom: 8,
  borderTopWidth: 1,
  borderTopColor: '#eee',
},
totalLabel: {
  fontSize: 16,
  fontWeight: '600',
  color: '#666',
},
totalAmount: {
  fontSize: 20,
  fontWeight: '800',
  color: '#111',
},
});
